<?php
/**
 * @author Emile Camara <camara.emile@gmail.com>
 * @project  defi-fullstack-app
 */
declare(strict_types=1);

namespace App\Shared\Domain\Exception;

enum ErrorCode : string
{
    case INVALID_REQUEST = 'INVALID_REQUEST';
    case STATION_NOT_FOUND = 'STATION_NOT_FOUND';
    case ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND';
    case NETWORK_DISCONNECTED = 'NETWORK_DISCONNECTED';
    case ANALYTIC_INVALID_PERIOD = 'ANALYTIC_INVALID_PERIOD';
    case UNKNOWN_ERROR = 'UNKNOWN_ERROR';
    case MISSING_PARAMETERS = 'MISSING_PARAMETERS';
    case ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND';
    case STATIONS_FILE_NOT_FOUND = 'STATIONS_FILE_NOT_FOUND';
    case STATIONS_FILE_EMPTY = 'STATIONS_FILE_EMPTY';
    case STATIONS_FILE_INVALID_JSON = 'STATIONS_FILE_INVALID_JSON';
    case DISTANCES_FILE_NOT_FOUND = 'DISTANCES_FILE_NOT_FOUND';
    case DISTANCES_FILE_INVALID_JSON = 'DISTANCES_FILE_INVALID_JSON';
    case DISTANCES_FILE_EMPTY = 'DISTANCES_FILE_EMPTY';
    case NEGATIVE_DISTANCE = 'NEGATIVE_DISTANCE';
    case EMPTY_PATH = 'EMPTY_PATH';
}
